#aws, dev, test 공통설정
# spring.mvc.view.prefix: /resorces/tmplates/
# spring.mvc.view.suffix: .html



server:
  port: 8080
spring:
  datasource: #Datasource 설정
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/oauth
      username: security
      password: security
      connection-timeout: 20000
      #pool-name: hikari-cp
      minimum-idle: 10
      maximum-pool-size: 2
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
      connection-test-query: SELECT 1


  servlet:
    multipart: #파일 업로드
      max-file-size: 30MB
      max-request-size: 30MB
      file-size-threshold: 10MB
      enabled: true




--- #aws 환경
spring:
  profiles:
      active: aws            
logging:
  file: logs/production_profile_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    jdbc.sqlonly: DEBUG
    jdbc.sqltiming: DEBUG
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    com.zaxxer.hikari.HikariDataSource: ERROR




--- #dev
spring:
  profiles:
      active: dev
  thymeleaf:
    cache: false
logging:
  pattern:
    console: "%msg%n"
  level:
    jdbc.resultset: DEBUG
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    com.zaxxer.hikari.HikariDataSource: DEBUG
    org.springframework.boot.context.properties.ConfigurationProperties: DEBUG


--- #test
spring:
  profiles:
      active: test
logging:
  file: logs/dev_profile_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    jdbc.sqlonly: DEBUG
    jdbc.sqltiming: DEBUG
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    com.zaxxer.hikari.HikariDataSource: ERROR
    

